In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [11]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.1186229 , -0.81369416, -0.16716809, ..., -1.25590025,
        -1.7670838 , -0.8698583 ],
       [-0.44629056,  0.36062172, -0.4248688 , ..., -0.07090507,
        -1.13032656,  0.08212952],
       [-0.16706073,  1.35772695, -0.18042601, ...,  0.05007531,
        -0.39293739, -0.53643536],
       ...,
       [-0.50327624, -0.52779432, -0.57194879, ..., -1.32940732,
        -1.6942124 , -1.36857268],
       [ 1.53681114,  1.36245256,  1.46231242, ...,  0.48192933,
        -1.01407933, -1.2782588 ],
       [-0.84803961,  3.44408695, -0.89552475, ..., -1.30337356,
         0.05817128, -0.58755643]], shape=(455, 30))

In [17]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [19]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,

In [150]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [151]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [22]:
class MySimpleNN():  #this is manual 

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


Using NN module for above manual 

In [23]:
import torch
import torch.nn as nn

In [24]:
class model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out= self.linear(features)
        out=self.sigmoid(out)

        return out
    

In [25]:
features = torch.rand(10,5)

In [26]:
model = model(features.shape[1])

In [28]:
#model.forward(features)
model(features)

tensor([[0.5591],
        [0.4899],
        [0.4690],
        [0.5382],
        [0.5256],
        [0.5738],
        [0.5478],
        [0.5553],
        [0.6288],
        [0.5795]], grad_fn=<SigmoidBackward0>)

Add Hidden Layer 


In [96]:
class model1(nn.Module):
    def __init__(self,num_features,num_hidden):
        super().__init__()
        self.linear= nn.Linear(num_features, num_hidden)
        self.reluLinear=nn.ReLU()
        self.hidden = nn.Linear(num_hidden,1)
        self.sigmoidHidden=nn.Sigmoid()


    def forward(self,features):
        out= self.linear(features)
        out=self.reluLinear(out)
        out=self.hidden(out)
        out=self.sigmoidHidden(out)

        return out

In [97]:
featuresLH = torch.rand(1000,50)
featuresLH

tensor([[0.0560, 0.0263, 0.2403,  ..., 0.2945, 0.5378, 0.1207],
        [0.7084, 0.7531, 0.1311,  ..., 0.8202, 0.0238, 0.6851],
        [0.4782, 0.2472, 0.2975,  ..., 0.2350, 0.1891, 0.1111],
        ...,
        [0.7793, 0.5462, 0.3696,  ..., 0.1785, 0.5618, 0.7817],
        [0.9005, 0.7163, 0.9471,  ..., 0.5598, 0.7431, 0.7800],
        [0.4381, 0.4456, 0.1856,  ..., 0.8885, 0.1080, 0.7366]])

In [98]:
model1=model1(50,7)



In [101]:
model1.linear.weight

Parameter containing:
tensor([[-0.1241, -0.0877, -0.1127, -0.0827, -0.0748, -0.0451,  0.1075,  0.0519,
          0.0079,  0.0804, -0.0535, -0.0926,  0.0145, -0.0257, -0.0781,  0.0300,
         -0.1265,  0.0509,  0.0293, -0.0900, -0.0505, -0.0908, -0.1278, -0.1282,
         -0.0047, -0.1042, -0.0699,  0.0824,  0.0169,  0.1409, -0.0592, -0.0546,
         -0.0781,  0.0852, -0.0506, -0.0609, -0.1068,  0.0300,  0.0571,  0.0632,
          0.0043, -0.1070, -0.1339,  0.0571,  0.1015,  0.0743,  0.0994, -0.1054,
         -0.0330,  0.0986],
        [-0.0530,  0.1030, -0.0560,  0.1103, -0.1105, -0.0847,  0.1066, -0.0128,
         -0.0373,  0.0460, -0.0826,  0.1189,  0.0491, -0.0550,  0.0920,  0.1257,
          0.1373, -0.0583, -0.1323,  0.0430, -0.0136,  0.0134,  0.0580, -0.1094,
          0.0417,  0.0608,  0.0950, -0.0215,  0.1035, -0.1256,  0.1060, -0.0654,
         -0.0657, -0.0315,  0.0643,  0.0827,  0.0792,  0.0166, -0.0159, -0.0080,
          0.1160, -0.0007, -0.0999,  0.0645, -0.1383, -0.08

Using Sequential to contain all the functions 

In [134]:
class modelSeq(nn.Module):
    def __init__(self,num_features,num_hidden):
        super().__init__()
        self.seq=nn.Sequential(
             nn.Linear(num_features, num_hidden),
             nn.ReLU(),
             nn.Linear(num_hidden,1),
             nn.Sigmoid()
        )


    def forward(self,features):
        out=self.seq(features)

        return out

In [135]:
featuresSeq = torch.rand(100,5)

In [136]:
model_seq=modelSeq(5,2)

In [137]:
model_seq(featuresSeq)

tensor([[0.5822],
        [0.5946],
        [0.5898],
        [0.5879],
        [0.5785],
        [0.5843],
        [0.5854],
        [0.5853],
        [0.5821],
        [0.5791],
        [0.5904],
        [0.5772],
        [0.5946],
        [0.5779],
        [0.5796],
        [0.5899],
        [0.5936],
        [0.5898],
        [0.5875],
        [0.5810],
        [0.5876],
        [0.5940],
        [0.5946],
        [0.5824],
        [0.5946],
        [0.5854],
        [0.5892],
        [0.5930],
        [0.5931],
        [0.5874],
        [0.5945],
        [0.5855],
        [0.5752],
        [0.5876],
        [0.5906],
        [0.5793],
        [0.5869],
        [0.5757],
        [0.5946],
        [0.5880],
        [0.5799],
        [0.5884],
        [0.5888],
        [0.5818],
        [0.5931],
        [0.5757],
        [0.5788],
        [0.5753],
        [0.5809],
        [0.5946],
        [0.5858],
        [0.5767],
        [0.5794],
        [0.5773],
        [0.5833],
        [0

Dl on CSV FIle 

In [ ]:
class MySimpleNN(nn.Module):  

  def __init__(self, firstLayer,Hidden1,Hidden2):
    super().__init__()
    self.seq=nn.Sequential(
      nn.Linear(firstLayer,Hidden1),
      nn.ReLU(),
      nn.Linear(Hidden1,Hidden2),
      nn.Sigmoid(),
      nn.Linear(Hidden2,1),
      nn.Sigmoid()
    )


  def forward(self,FeaturesSeq):
    out=self.seq(FeaturesSeq)
    return out

  

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [168]:
learning_rate=0.1
epochs=25

In [169]:
#create model

print(X_test_tensor.shape[0])  # number of samples
print(X_test_tensor.shape[1])  # number of features (if 2D)


114
30


In [170]:
modelnew=MySimpleNN(X_test_tensor.shape[1],5,5)

In [ ]:
for epoch in range(epochs):
    y_pred = modelnew(X_train_tensor)

loss=modelnew.loss_function(y_pred, y_train_tensor)

loss.backward()

with torch.no_grad():

    modelnew.seq[0].weight -= learning_rate * modelnew.seq[0].weight.grad
    modelnew.seq[0].bias   -= learning_rate * modelnew.seq[0]r.bias.grad

modelnew.seq[0].weight.grad.zero_()
modelnew.seq[0].bias.grad.zero_()


tensor([0., 0., 0., 0., 0.])

Loss Function Build in 

In [179]:
class MySimpleNN2(nn.Module):  #this is manual 

  def __init__(self, new_features):
    super().__init__()
    self.linear=nn.Linear(new_features,1)
    self.sigmoid =nn.Sigmoid
    


  def forward(self,Features):
    out=self.seq(Features)
    return out

  


In [182]:
loss_function = nn.BCELoss()
modelnew=MySimpleNN2(X_train_tensor.shape[1])


In [184]:
for epoch in range(epochs):
    y_pred = modelnew(X_train_tensor)

loss = loss_function(y_pred,y_train_tensor.view(-1,1))

loss.backward()

with torch.no_grad():

    modelnew.linear.weight -= learning_rate * modelnew.linear.weight.grad
    modelnew.linear.bias   -= learning_rate * modelnew.linear.bias.grad

modelnew.linear.weight.grad.zero_()
modelnew.linear.bias.grad.zero_()

AttributeError: 'MySimpleNN2' object has no attribute 'seq'